version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:  python -m debugpy --listen 0.0.0.0:5678 -m app --wait-for-client --multiprocess -m FLASK_APP=app.py flask run -h 0.0.0.0 -p 5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - ./.env.dev
    stdin_open: true
    depends_on:
      - db
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - 5432:5432

volumes:
  pgdata: